### PR TITLE
Bump oldcpu to 0.14.1

### PR DESCRIPTION
**Pull request by Crazypersonalph**
cc @blakeblackshear @NickM-27

### CODE REVIEW

**Review by NickM-27 — APPROVED** [review]

**Comment by Crazypersonalph** [comment]
@blakeblackshear any update on when this can be merged?

**Comment by fcaronte** [comment]
So new .14 is work on old cpu without anx? I want to try update my old server actually I have this version and 4.0 on Hass plugin

**Comment by Crazypersonalph** [comment]
> So new .14 is work on old cpu without anx? I want to try update my old server actually I have this version and 4.0 on Hass plugin
> 
> 
> 

Your screenshot looks like it is running v13 of Frigate instead of v14

**Comment by Crazypersonalph** [comment]
I have been daily driving this version for around about half a month now and I have experienced no problems.

**Comment by fcaronte** [comment]
> I have been daily driving this version for around about half a month now and I have experienced no problems.

Yes because was the only I was able to make work on that pc using GPU power. Yesterday for example I try to create a new lxc with proxmox script helper on my main server and all is okay with last version but same step on the old pc install but then is not working correctly I have no data I can't go in the settings and other problems, I need to try with that version when have some time and see if work for me too

**Comment by fcaronte** [comment]
> I have been daily driving this version for around about half a month now and I have experienced no problems.

i download your fork then i make an image from the old cpu folder and use on portainer to update my frigate container and seem work correctly with gpu :)

PS. i need to test a little more because seem to use more cpu too vs the v12 i was using before, and this server is only dual core with 4gb ram  +512 amd gpu

image

**Comment by fcaronte** [comment]
ahahah poor notebook

image

**Comment by fcaronte** [comment]
Hi @Crazypersonalph i update again from your fork to the last 14.1 and upload to my old pc with this tag name:  "frigate-14.1-old-cpu" I'm not understood if is public or not but image seem working correctly

**Comment by Crazypersonalph** [comment]
> Hi @Crazypersonalph i update again from your fork to the last 14.1 and upload to my old pc with this tag name: "frigate-14.1-old-cpu" I'm not understood if is public or not but image seem working correctly

Hello,
As of right now there are no pre-built images of the oldcpu Dockerfile, you will have to compile it yourself.
This pull request is still yet to be upgraded to 14.1.

Kind Regards

**Comment by Crazypersonalph** [comment]
Version has now been bumped

**Comment by fcaronte** [comment]
> > Hi @Crazypersonalph i update again from your fork to the last 14.1 and upload to my old pc with this tag name: "frigate-14.1-old-cpu" I'm not understood if is public or not but image seem working correctly
> 
> Hello,
> As of right now there are no pre-built images of the oldcpu Dockerfile, you will have to compile it yourself.
> This pull request is still yet to be upgraded to 14.1.
> 
> Kind Regards

Yes I do, I wrote the img tag name I put because I don't know if when I load to portainer then is visible for all on only for me, it show a message about you can load xx thing in max 6hour , I don't remember exactly 🤣

**Comment by fcaronte** [comment]
@Crazypersonalph I have a question for you, yesterday I noted that I'm was able to use GPU only for ffmpeg but detector still use CPU and make my notebook to have high temperature and CPU load. Do you think I can make work GPU for detector too? I don't take care if this problem happens with V12 of frigate too

**Comment by Crazypersonalph** [comment]
> @Crazypersonalph I have a question for you, yesterday I noted that I'm was able to use GPU only for ffmpeg but detector still use CPU and make my notebook to have high temperature and CPU load. Do you think I can make work GPU for detector too? I don't take care if this problem happens with V12 of frigate too

You can, with either OpenVINO (Intel GPU) or TensorRT (Nvidia GPU)
Not sure about AMD though.
https://docs.frigate.video/configuration/object_detectors

Kind Regards

**Comment by Crazypersonalph** [comment]
For the time being if you want pre-built builds, you can get the latest stable version of Frigate for oldcpus from here:
ghcr.io/crazypersonalph/frigate_oldcpu

**Comment by Crazypersonalph** [comment]
There are now version numbers on the container, starting from 0.14.1

**Comment by fcaronte** [comment]
> There are now version numbers on the container, starting from 0.14.1
> 
> ghcr.io/crazypersonalph/frigate_oldcpu:0.14.1

thanks i'll try to see if work the same as my self compiled version

**Comment by fcaronte** [comment]
> There are now version numbers on the container, starting from 0.14.1
> 
> ghcr.io/crazypersonalph/frigate_oldcpu:0.14.1

At the end After a lot of try I give up and come back to v12, last 14 need to power for my old pc and use to much CPU making temperature go crazy, but yes was a good test and img work correctly

**Comment by Crazypersonalph** [comment]
Any update on when this can be merged?

**Pull request merged**
