### PR TITLE
0.12 Beta4

### PR DESCRIPTION
**Pull request by NickM-27**
This is just a placeholder for when beta 4 is ready

- Map 8555 tcp and udp
- I made the webrtc ports mapped by default because I believe when go2rtc isn't looking for a connection there is no data exposed or accessible. May need to do more consideration for this.

### CODE REVIEW

**Comment by felipecrs** [comment]
I'm just wondering here, does the 8554 port need to be forwarded for viewing from Home Assistant? If so, it would be perhaps a good idea to have it forwarded by default.

**Comment by NickM-27** [comment]
> I'm just wondering here, does the 8554 port need to be forwarded for viewing from Home Assistant? If so, it would be perhaps a good idea to have it forwarded by default.

Yes it's needed but we don't want to auto forward anything that gives unauthenticated access to sensitive info. This would be the case for 8554 so it should not be auto mapped

**Comment by NickM-27** [comment]
Also I think the ingress part may be usable as well

**Comment by felipecrs** [comment]
Sure. Thank you.

**Review by blakeblackshear — APPROVED** [review]

**Pull request merged**
