### PR TITLE
Remove Rockchip Addon

### PR DESCRIPTION
**Pull request by NickM-27**
Based on the conversation in https://github.com/blakeblackshear/frigate-hass-addons/issues/145 HA OS does not include the necessary kernel to use the RK hardware so the addon will be unable to work. The addon should be removed to avoid confusion for users.

### CODE REVIEW

**Comment by fensoft** [comment]
Hi,

You've removed rockchip but for thoses like me that are using HA Supervised, it can be very useful.
I've forked on my side and i'll send you a PR in few days.

**Comment by NickM-27** [comment]
Have you read the reason why it was removed? Because it did not work...

**Comment by fensoft** [comment]
Installed an armbian on several boards, installed HA supervised and got it working with 3 streams in hardware decoding. I'm searching for a way to decode more streams but for me it's enough to enable it back.

**Comment by NickM-27** [comment]
the setup you are describing is not supported by HA, only debian is supported. and in this case supervised has been deprecated and will lose support at the end of the year.

Unless this works in HA OS, then it does not make sense to add the addon

**Comment by fensoft** [comment]
armbian is very very similar to debian. also have a rockchip board bundled with debian and it works too.

**Comment by fensoft** [comment]
also, HAOS officialy supports this board: https://wiki.odroid.com/odroid-m1s/odroid-m1s

**Comment by NickM-27** [comment]
> also, HAOS officialy supports this board: https://wiki.odroid.com/odroid-m1s/odroid-m1s

yes, but the correct configuration for the addon was not available in HA OS. And since supervised installations are soon to be unsupported by HomeAssistant, we can only have the add-on if it works in HA OS.

**Comment by fensoft** [comment]
maybe we can find a way to hide it by default ? i prefer not handling updates on my side.

**Comment by fensoft** [comment]
> supervised installations are soon to be unsupported by HomeAssistant

it's not written on the official [specification](https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md). do you have a link about this ?

**Comment by NickM-27** [comment]
https://community.home-assistant.io/t/deprecating-core-and-supervised-installation-methods-and-32-bit-systems/893617

**Pull request merged**
